export const ROADMAP = [
  {
    version: "V1",
    name: "Le Studio IA",
    status: "Terminée",
    goal: "Créer un produit digital complet et son marketing en une après-midi.",
    features: [
      { label: "Fiche produit unique partagée par tous les modules", done: true },
      { label: "Ebook complet (sommaire, chapitres, points clés) + export PDF", done: true },
      { label: "Templates imprimables : planners, checklists, workbooks, trackers", done: true },
      { label: "Couverture IA + mockups 3D (livre, tablette, smartphone, pack) + visuels pub", done: true },
      { label: "Pages de vente (PAS, AIDA, storytelling) avec mockup intégré", done: true },
      { label: "Sites vitrines one-page responsives", done: true },
      { label: "Scripts vidéo UGC & storytelling + vidéo avec avatar IA (HeyGen)", done: true },
      { label: "Bibliothèque de projets (stockée dans le navigateur)", done: true },
    ],
  },
  {
    version: "V2",
    name: "Le SaaS commercialisable",
    status: "En cours",
    goal: "Transformer le studio en abonnement payant, multi-utilisateurs.",
    features: [
      { label: "Comptes utilisateurs (email, Google) et base de données", done: true },
      { label: "Abonnements Starter / Pro / Business : Stripe + Mobile Money", done: true },
      { label: "Crédits de génération par mois et suivi de la consommation", done: true },
      { label: "Éditeur visuel : modifier textes, couleurs et images après génération", done: false },
      { label: "Images générées par IA pour couvertures, sites et pages de vente", done: false },
      { label: "Hébergement en 1 clic des sites et pages de vente (sous-domaine + domaine perso)", done: false },
      { label: "3 variantes par génération pour choisir la meilleure", done: false },
      { label: "Stockage cloud des projets, images et vidéos", done: true },
    ],
  },
  {
    version: "V3",
    name: "La machine de vente",
    status: "Plus tard",
    goal: "Vendre, diffuser et optimiser automatiquement.",
    features: [
      { label: "Boutique intégrée + publication vers Chariow, Gumroad, Selar", done: false },
      { label: "Vidéos UGC avancées : B-roll IA (Runway, Kling), plusieurs avatars, montage auto", done: false },
      { label: "Programmation des publications TikTok, Instagram, Facebook", done: false },
      { label: "Tests A/B des pages de vente et des hooks vidéo", done: false },
      { label: "Statistiques : visites, conversions, ventes par produit", done: false },
      { label: "Séquences emails et WhatsApp générées par IA", done: false },
      { label: "Marketplace de templates entre créateurs + affiliation", done: false },
      { label: "Mode agence : équipes, clients multiples, marque blanche, API", done: false },
    ],
  },
] as const;
