export const ROADMAP = [
  {
    version: "V1",
    name: "Le Studio IA",
    status: "Disponible",
    goal: "Créer un produit digital complet et son marketing en une après-midi.",
    features: [
      "Fiche produit unique partagée par tous les modules",
      "Ebook complet (sommaire, chapitres, points clés) + export PDF",
      "Templates imprimables : planners, checklists, workbooks, trackers",
      "Couverture IA + mockups 3D (livre, tablette, smartphone, pack) + visuels pub",
      "Pages de vente (PAS, AIDA, storytelling) avec mockup intégré",
      "Sites vitrines one-page responsives",
      "Scripts vidéo UGC & storytelling + vidéo avec avatar IA (HeyGen)",
      "Bibliothèque de projets (stockée dans le navigateur)",
    ],
  },
  {
    version: "V2",
    name: "Le SaaS commercialisable",
    status: "Prochaine étape",
    goal: "Transformer le studio en abonnement payant, multi-utilisateurs.",
    features: [
      "Comptes utilisateurs (email, Google) et base de données",
      "Abonnements Starter / Pro / Business : Stripe + Mobile Money",
      "Crédits de génération par mois et suivi de la consommation",
      "Éditeur visuel : modifier textes, couleurs et images après génération",
      "Images générées par IA pour couvertures, sites et pages de vente",
      "Hébergement en 1 clic des sites et pages de vente (sous-domaine + domaine perso)",
      "3 variantes par génération pour choisir la meilleure",
      "Stockage cloud des PDF, images et vidéos",
    ],
  },
  {
    version: "V3",
    name: "La machine de vente",
    status: "Plus tard",
    goal: "Vendre, diffuser et optimiser automatiquement.",
    features: [
      "Boutique intégrée + publication vers Chariow, Gumroad, Selar",
      "Vidéos UGC avancées : B-roll IA (Runway, Kling), plusieurs avatars, montage auto",
      "Programmation des publications TikTok, Instagram, Facebook",
      "Tests A/B des pages de vente et des hooks vidéo",
      "Statistiques : visites, conversions, ventes par produit",
      "Séquences emails et WhatsApp générées par IA",
      "Marketplace de templates entre créateurs + affiliation",
      "Mode agence : équipes, clients multiples, marque blanche, API",
    ],
  },
] as const;
